### ISSUE TITLE
Batches retrieval with same creation date

### ISSUE THREAD

**Issue by JonathanIN** [eu-digital-green-certificates/dgca-revocation-distribution-service#16]
Hi, 

While running some tests, it appears that some batches are missing on our side when synchronising using the revocation-distribution-service. 

Not sure if it's a bug or if this is a misunderstanding from our side...

Let's assume the following (weird) example : 
There are : 
- 1001 batches added at the EXACT same date : 2022-06-14T14:30:00
- 5 batch added at a later time : 2022-06-14T16:00:00
- the last fetching date of the service is the day before : 2022-06-13T20:00:00

I believe that at the next synchronisation : 
1. The service will request the modification since the last update using If-Modified-Since=2022-06-13T20:00:00
2. The GW will provide the new batches after this date but limited to 1000 entries (I assume that the service use the API revocation-list from the gateway) so the first 1000 batches added at 2022-06-14T14:30:00 and inform that they are more batched (more=true)
3. The service will request the modification using the date of the last batches received from the previous request, i.e If-Modified-Since=2022-06-14T14:30:00
4. In this case, it looks like that the GW provide the batches AFTER this date (not equal or greater but strictly greater), so in this case, it will return the 5 batches with date 2022-06-14T16:00:00
**> Meaning that the last batch from the 1001 batches at 2022-06-14T14:30:00 will not be returned.** 

Is that correct? If not, how does it work to retrieve the last batch of the 1001 batches with the same date?

Thanks,

**Comment by JonathanIN** [comment]
It's actually a 2 part question : 
1. How do I retrieve all the batches in this example using the API GET /revocation-list of the GW (and the field If-Modified-Since)?
2. How does it work in the dgca-revocation-distribution-service in this example?

**Comment by JonathanIN** [comment]
To be clear : it does not required to have 1001 batches with the same date (it was a simplification), only to have a few batches with the exact same date and a limit to 1000 batches that occurs in this group of batches : 
- 999 batches added between  : 2022-06-14T08:30:00 and 2022-06-14T11:30:00
- 2 batches added at the EXACT same date : 2022-06-14T14:30:00
- 5 batch added at a later time : 2022-06-14T16:00:00
- the last fetching date of the service is the day before : 2022-06-13T20:00:00

**Comment by chrloch** [comment]
This is a consequence of https://github.com/eu-digital-green-certificates/dgc-gateway/issues/159

It is recognized as a bug but was given a low priority since it was assumed that the probability of such an event would be really small in the real world. 

A safer implementation of the distribution service could implement the suggested mitigation from the other bug: To resume the download not at the split date-time but 1 second earlier so that - with possible overlap - no batch is missed. 

(This will mitigate the bug if less than 999 batches have the exact same timestamp, which should be safe enough for real world use)

**Comment by JonathanIN** [comment]
thank you
