### ISSUE TITLE
Missing batches after synchronisation

### ISSUE THREAD

**Issue by JonathanIN** [eu-digital-green-certificates/dgca-revocation-distribution-service#17]
Hello, 

We uploaded 134 batches to the gateway but after synchronisation using the dgca-revocation-distribution-service, only 127 batches were retrieved. 

When looking into the log, we have 7 errors, corresponding to the 7 missing batches, of this type:
2022-06-30 16:51:09,058 ERROR [scheduling-2] eu.europa.ec.dgc.gateway.connector.DgcGatewayRevocationListDownloadConnector : Download of revocation list batch failed. DGCG responded with status code: 200
2022-06-30 16:51:09,058 ERROR [scheduling-2] eu.europa.ec.dgc.revocationdistribution.service.RevocationListDownloadServiceGatewayImpl : Batch download failed

Why is this happening? What should be do if this error occured to retrieve the failed batches?

Thank you,
Jonathan

**Comment by chrloch** [comment]
After a first analysis we couldn't find out why it would go into this state. 
Could you attach or send logs from the time before the error occured? 

This is should be the part in the code: 
https://github.com/eu-digital-green-certificates/dgc-lib/blob/be85ebdfb9d5b3a1639d723ce9a7a781fbff62a2/src/main/java/eu/europa/ec/dgc/gateway/connector/DgcGatewayRevocationListDownloadConnector.java#L89

**Comment by JonathanIN** [comment]
[dgca-revocation-distribution-service-2022-06-30.log](https://github.com/eu-digital-green-certificates/dgca-revocation-distribution-service/files/9070375/dgca-revocation-distribution-service-2022-06-30.log)

You can find attach an example of log with this error.
